Addons update
charmed-kubernetes/kubernetes-docs pull request #697
Opened 2022-06-30 13:30 UTC by evilnick

This is still a WIP as I need to do all the steps for the Howto page

2022-06-30 14:34 UTC, evilnick commented on pages/k8s/cdk-addons.md
> +<div class="p-notification--positive is-inline">
N.B. this doesn't display correctly in our preview due to changes in vanilla used in u.c. I will try and sync these at a future date

2022-06-30 14:35 UTC, evilnick commented on pages/k8s/how-to-addons.md
> +
This page is obviously still very much WIP

2022-08-04 15:26 UTC, stonepreston requested changes

2022-08-04 15:26 UTC, stonepreston commented on pages/k8s/cdk-addons.md
> +If you use the operator charm to deploy CorDNS to your cluster instead,
```suggestion
If you use the operator charm to deploy CoreDNS to your cluster instead, 
```

2022-08-04 15:26 UTC, stonepreston commented on pages/k8s/how-to-addons.md
> +juju relate -m cluster-model coredns kubernetes-control-plane
```suggestion
juju relate -m ck-model coredns kubernetes-control-plane
```

2022-08-04 15:32 UTC, evilnick commented on pages/k8s/how-to-addons.md
> +juju relate -m cluster-model coredns kubernetes-control-plane
good spot - I thought I'd changed all those!

2022-08-05 10:48 UTC, merged