update ha page and images
charmed-kubernetes/kubernetes-docs pull request #802
Opened 2023-10-05 01:17 UTC by evilnick

woke-checker isn't so good at images

2023-10-05 20:20 UTC, Cynerva requested changes
This doc often shortened "master unit" to simply "master". With these updates, it shortens "control plane unit" to "control plane" in the same way. I think that could lead to confusion since "control plane" usually refers to the whole control plane including all kubernetes-control-plane units.

See my suggested changes that I hope will clear this up a bit.

2023-10-05 20:20 UTC, Cynerva commented on pages/k8s/high-availability.md
> +always use that control plane unit. This means if that control plane fails in a way that
```suggestion
happens is that the workers will randomly pick a control plane unit to communicate with and
always use that unit. This means if that control plane unit fails in a way that
```

2023-10-05 20:20 UTC, Cynerva commented on pages/k8s/high-availability.md
> +also overload the control plane with traffic, making the additional units redundant.
```suggestion
with the control plane. If workers arbitrarily pick the same control plane unit, they can
also overload the unit with traffic, making the additional units redundant.
```

2023-10-05 20:20 UTC, Cynerva commented on pages/k8s/high-availability.md
> +Load balancing the control planes is the next logical step:
```suggestion
Load balancing the control plane is the next logical step:
```

2023-10-05 20:20 UTC, Cynerva commented on pages/k8s/high-availability.md
> +you want high availability on the control plane, multiple control planes floating a
```suggestion
you want high availability on the control plane, multiple control plane units floating a
```

2023-10-06 14:43 UTC, evilnick commented
@Cynerva thanks for that, I guess I should have given it another readthrough but all those masters and control planes just started sounding like gobbledygook at some point

2023-10-06 16:22 UTC, Cynerva approved these changes

2023-10-06 17:06 UTC, merged